seed: 42
data:
  articles_path: data/articles.csv
  customers_path: data/customers.csv
  transactions_path: data/transactions_train.csv
  past_start_date: 2020-09-01
  past_end_date: 2020-09-04
  train_start_date: 2020-09-05
  train_end_date: 2020-09-05
  val_start_date: 2020-09-06
  val_end_date: 2020-09-06
  test_start_date: 2020-09-07
  test_end_date: 2020-09-07
  chunksize: 100000
  num_customer: 10000
  customer:
    usecols:
      [
        "customer_id",
        "FN",
        "Active",
        "club_member_status",
        "fashion_news_frequency",
        "age",
        # "postal_code",
      ]
  article:
    usecols:
      [
        "article_id",
        "product_code",
        "colour_group_name",
        "department_name",
        "department_no",
        "garment_group_name",
        "graphical_appearance_name",
        "index_group_name",
        "index_name",
        "perceived_colour_master_name",
        "perceived_colour_value_name",
        "product_group_name",
        "product_type_name",
        "section_name",
        # "detail_desc",
      ]
candidates:
  popular:
    topk: 20
  age_popular:
    topk: 20
  most_freq_cat_popular:
    topk: 20
  similar:
    min_df: 3
    topk: 20
  item2vec:
    topk: 20
  cooc:
    topk: 10
  node2vec:
    topk: 20
  transition:
    topk: 20
  faiss:
    topk: 20
  use:
    [
      "popular",
      "age_popular",
      "user_past",
      "most_freq_cat_popular",
      "same_product",
      "item2vec",
      "cooc",
      "ttm",
    ]
model:
  features:
    num:
      [
        "item_purchase_cnt",
        "item_purchase_nunique",
        "item_days_since_last_purchase",
        "item_price_mean",
        "item_price_std",
        "user_purchase_cnt",
        "user_purchase_nunique",
        "user_days_since_last_purchase",
        "user_price_mean",
        "user_price_std",
        "user_price_sum",
        "user_item_purchase_cnt",
        "age",
        "item2vec_affinity_score",
        "ttm_affinity_score",
      ]
    cat:
      [
        "FN",
        "Active",
        "club_member_status",
        "fashion_news_frequency",
        "colour_group_name",
        "department_name",
        "department_no",
        "garment_group_name",
        "graphical_appearance_name",
        "index_group_name",
        "index_name",
        "perceived_colour_master_name",
        "perceived_colour_value_name",
        "product_group_name",
        "product_type_name",
        "section_name",
      ]
  params:
    lgb:
      objective: lambdarank
      eval_metric: ["ndcg"]
      eval_at: [1, 3, 5, 10]
      max_depth: 5
      learning_rate: 0.01
      n_estimators: 1000
      importance_type: gain
      early_stopping_round: 50
    cat:
      loss_function: YetiRank
      eval_metric: NDCG:top=10
      iterations: 1000
      learning_rate: 0.01
      depth: 5
      early_stopping_round: 50
    item2vec:
      vector_size: 64
      window: 5
      min_count: 3
      workers: 0
      sg: 1
    cooc:
      n_components: 64
      use_ppmi: true
    node2vec:
      dimensions: 64
      p: 1.0
      q: 1.0
      walk_length: 5
      num_walks: 20
      workers: 1
      window: 8
      min_count: 5
    ttm:
      user_num_cols: ["age"]
      item_num_cols: []
      user_cat_cols:
        ["FN", "Active", "club_member_status", "fashion_news_frequency"]
      item_cat_cols:
        [
          "colour_group_name",
          "department_name",
          "department_no",
          "garment_group_name",
          "graphical_appearance_name",
          "index_group_name",
          "index_name",
          "perceived_colour_master_name",
          "perceived_colour_value_name",
          "product_group_name",
          "product_type_name",
          "section_name",
        ]
      cat_max_dims: 8
      item_cat_dims: []
      item_cat_hidden_size: 8
      item_num_hidden_size: 8
      user_cat_dims: []
      user_cat_hidden_size: 8
      user_num_hidden_size: 8
      emb_size: 8
      train_batch_size: 4
      num_workers: 0
reranker:
  mmr_item2vec:
    w: 0
exp:
  num_rec: 10
  ks: [1, 3, 5, 10]
  summary_plot_num_sample: 10000
